to avoid creating folders for misspelled parametes

diff --git a/data/FaCy/diffs/facyapp.diff b/data/FaCy/diffs/facyapp.diff
--- a/data/FaCy/diffs/facyapp.diff
+++ b/data/FaCy/diffs/facyapp.diff
@@ -120,3 +120,24 @@
      cp \
          "/var/lxr/${USER}/LinExRoot_git/LinExRoot/1Tux/FaCyApp/facyapp" \
          "/mnt/LinEx/Root/1Tux/${USER}/FaCyApp/facyapp"
+--- /mnt/LinEx/Root/1Tux/nkpro/FaCyApp/facyapp	2023-07-21 22:36:45.986392935 +0530
++++ /var/lxr/nkpro/LinExRoot_git/LinExRoot/1Tux/FaCyApp/facyapp	2023-08-03 21:30:38.080623241 +0530
+@@ -99,6 +99,18 @@
+ mkdir -p "/mnt/LinEx/Root/1Tux/${USER}/FaCyApp/.HOMEs/"
+ ln -sfT "/mnt/LinEx/Root/1Tux/${USER}/FaCyApp/.HOMEs/" "/mnt/LinEx/Root/1Tux/${USER}/.~" || exit 2
+ 
++if test ! -d "/mnt/LinEx/Root/1Tux/${USER}/FaCyApp/.HOMEs/$home/" -o \
++        ! -d "/mnt/LinEx/Root/1Tux/${USER}/FaCyApp/.CryFs/$home/$app/" -o \
++        ! -f "/mnt/LinEx/Root/1Tux/${USER}/FaCyApp/.init/$home/$app.sh" ; then
++    echo "I> Home folder / CryFs folder / init script  NOT FOUND"
++    echo "<> Enter c:to create | *:to abort >"
++    read -r abort
++    if test "$abort" != 'c'; then
++        echo "|> Aborting ..."
++        exit
++    fi
++fi
++
+ home_path="/mnt/LinEx/Root/1Tux/${USER}/.~/$home/"
+ if test ! -d "$home_path"; then
+     echo "|> Home folder not found : $home_path"
diff --git a/data/FaCy/diffs/facyfox.diff b/data/FaCy/diffs/facyfox.diff
--- a/data/FaCy/diffs/facyfox.diff
+++ b/data/FaCy/diffs/facyfox.diff
@@ -106,3 +106,23 @@
      cp \
          "/var/lxr/${USER}/LinExRoot_git/LinExRoot/1Tux/FaCyFox/facyfox" \
          "/mnt/LinEx/Root/1Tux/${USER}/FaCyFox/facyfox"
+--- /mnt/LinEx/Root/1Tux/nkpro/FaCyFox/facyfox	2023-07-21 22:36:41.649725797 +0530
++++ /var/lxr/nkpro/LinExRoot_git/LinExRoot/1Tux/FaCyFox/facyfox	2023-08-03 21:30:30.360072948 +0530
+@@ -70,6 +70,17 @@
+     exit 1
+ fi
+ 
++if test ! -d "/mnt/LinEx/Root/1Tux/${USER}/FaCyFox/.FireFox/$name/" -o \
++        ! -d "/mnt/LinEx/Root/1Tux/${USER}/FaCyFox/.CryFs/$name/" ; then
++    echo "I> FireFox Profile folder / CryFs folder  NOT FOUND"
++    echo "<> Enter c:to create | *:to abort >"
++    read -r abort
++    if test "$abort" != 'c'; then
++        echo "|> Aborting ..."
++        exit
++    fi
++fi
++
+ home_path="/mnt/LinEx/Root/1Tux/${USER}/FaCyFox/.FireFox/$name/"
+ if test ! -d "$home_path"; then
+     echo "|> Home folder for FireFox not found : $home_path"
